repos:
  # Ruff - Python linter and formatter (replaces multiple tools)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, pyi]
        exclude: >
          (?x)^(
            \.venv/
            |build/
            |dist/
            |node_modules/
            |__pycache__/
            |\.git/
            |\.mypy_cache/
          )
        verbose: true

  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]
        exclude: >
          (?x)^(
            \.venv/
            |build/
            |dist/
            |node_modules/
            |__pycache__/
            |\.git/
          )

  # Basic file utilities
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=5000]
