name: Ruff

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        run: |
          ruff check . --extend-exclude '
            ^(
              \.venv/
              |build/
              |dist/
              |\.git/
              |\.mypy_cache/
              |__pycache__/
              |\.github/
              |.*\.ya?ml$  # Exclude YAML files
            )
          '
          ruff format --check . --extend-exclude '
            ^(
              \.venv/
              |build/
              |dist/
              |\.git/
              |\.mypy_cache/
              |__pycache__/
              |\.github/
              |.*\.ya?ml$  # Exclude YAML files
            )
          '
        env:
          # Only needed if your project has a pyproject.toml with custom config
          RUFF_FORMAT_INDENT_STYLE: space
          RUFF_FORMAT_INDENT_WIDTH: 4
          RUFF_FORMAT_QUOTE_STYLE: double
