name: Ruff

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff checks
        run: |
          # Run Ruff linter with exclusions
          ruff check . --extend-exclude '
            ^(
              \.venv/
              |build/
              |dist/
              |\.git/
              |\.mypy_cache/
              |__pycache__/
              |\.github/
              |.*\.ya?ml$
            )
          '
          # Run Ruff formatter with check mode
          # Note: --exclude is not supported in ruff format, so we'll use find to filter files
          find . -type f -name '*.py' | \
            grep -vE '/(\.venv|build|dist|\.git|\.mypy_cache|__pycache__|\.github)/' | \
            xargs ruff format --check
        env:
          # Only needed if your project has a pyproject.toml with custom config
          RUFF_FORMAT_INDENT_STYLE: space
          RUFF_FORMAT_INDENT_WIDTH: 4
          RUFF_FORMAT_QUOTE_STYLE: double
